apiVersion: v1
kind: Service
metadata:
  name: brms
  namespace: ingress-nginx
  labels:
    app: brms
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: brms
  externalTrafficPolicy: Local
