apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: ingress-nginx
spec:
  # Use the name of the IngressClass that your ingress-nginx chart created:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.conexus-dev-sandbox.org
      secretName: let-encrypt-ssl-secret
  rules:
    - host: app.conexus-dev-sandbox.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-nginx-ingress-nginx-controller
                port:
                  number: 80