apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx
resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

#  Bamboo rewrites these newTag values on each release
images:
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-jboss-portal
    newTag: 8.0.8-ui97-rest170.100
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-jboss-jms
    newTag: 8.0.8-task210.100
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-jboss-webservice
    newTag: 8.0.8-ws148.100-cnxs169.100-dpa128.100
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-jboss-brms
    newTag: 8.0.8-recon144.100-cmod44.100-swag136.100
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-jboss-reporting
    newTag: 8.0.8-repo110.100-vend136.100