apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config2
  namespace: wso2mi 
data:
  app_key: DEVSUXENOC
  tenant_key: fbe58f4c-96f3-449e-8d52-306526d56049
  socn_path: http://webservice.ingress-nginx.svc.cluster.local:8080/ws-services-order-services-impl/SOCNService/SOCN
  SERVER_NAME: mi.conexus-project.org
