apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config2
  namespace: ingress-nginx
data:
  socn_path: http://webservice.ingress-nginx.svc.cluster.local:8080/ws-services-order-services-impl/SOCNService/SOCN
  SERVER_NAME: ${miurl}
