apiVersion: v1
kind: Service
metadata:
  name: conexus-wso2mi
  namespace: ingress-nginx
  labels:
    app: conexus-wso2mi
spec:
  ports:
    - name: http-passthrough
      port: 8290
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: conexus-wso2mi
  externalTrafficPolicy: Local

