apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cnxsdev-selfmanaged
  region: us-east-1

nodeGroups:
  - name: cnxsdev-selfmanaged-node-a
    kubeletExtraConfig:
        clusterDNS: [ "172.20.0.10" ]
