apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
generatorOptions:
  disableNameSuffixHash: true # stable names for mounts

configMapGenerator:
  - name: jboss-brms-config
    files:
      - standalone-full.xml=../config/standalone-full.xml.brms8
  - name: jboss-jms-config
    files:
      - standalone-full.xml=../config/standalone-full.xml.jms8
  - name: jboss-portal-config
    files:
      - standalone-full.xml=../config/standalone-full.xml.portal8
  - name: jboss-reporting-config
    files:
      - standalone-full.xml=../config/standalone-full.xml.reporting8
  - name: jboss-webservice-config
    files:
      - standalone-full.xml=../config/standalone-full.xml.webservice8
  - name: jboss-brms-custom-config
    files:
      - customconfig.properties=../config/customconfig.properties

resources:
  - services/brms-svc.yaml
  - services/jms-svc.yaml
  - services/portal-svc.yaml
  - services/reporting-svc.yaml
  - services/webservice-svc.yaml
  - deployments/brms-deploy.yaml
  - deployments/jms-deploy.yaml
  - deployments/portal-deploy.yaml
  - deployments/reporting-deploy.yaml
  - deployments/webservice-deploy.yaml
