apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: ingress-nginx
data:
  SERVER_NAME: ${uiurl}
  AVSERVER: avapache
  OIDC_PROVIDER_URL: ${oidc_provider_url}
  OIDC_CLIENT_ID: ${oidc_client_id}
  OIDC_REDIRECT_URI: ${oidc_redirect_uri}
  OIDC_LOGGEDOUT_URL: ${oidc_loggedout_url}
  OIDC_DEFAULT_URL: ${oidc_default_url}

 
