apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base

images:
  - name: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-apache
    newName: 339713019047.dkr.ecr.us-east-1.amazonaws.com/conexus-apache
    newTag: "1.3"