apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config2
  namespace: ingress-nginx
data:
  SOCN_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/ws-services-order-services-impl/SOCNService/SOCN
  ATAX_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/tax-services/ATAXService/AllowableTax
  SOA_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/SOAService/SOA
  SOC_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/SOCService/SOC
  SOAC_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/SOACService/SOAC
  FOCN_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/FOCNService/FOCN
  SORN_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/SORNService/SORN
  SSCN_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/SSCNService/SSCN
  DBAS_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/order-services/DBASService/DBAS
  HEALTHCHK_PATH: http://webservice.ingress-nginx.svc.cluster.local:8080/ws-services-health-check/HealthCheckService/HealthCheck
  SO_ATT_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/att/so
  SO_BTF_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/btfederal/so
  SO_CENTURYLINK_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/centurylink/so
  SO_CORETECH_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/coretech/so
  SO_GRANITE_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/granite/so
  SO_METTEL_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/mettel/so
  SO_MICROTECH_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/microtech/so
  SO_VERIZON_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/verizon/so
  SO_HARRIS_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/outbound/harris/so
  PEGASYS_REF_PATH: http://forwardproxy.ingress-nginx.svc.cluster.local/eas/conexus/pegasys/outbound/refservice
  NGINX_HOST: http://forwardproxy.ingress-nginx.svc.cluster.local
  NGINX_PORT: "80"
  JBOSS_HOST: http://webservice.ingress-nginx.svc.cluster.local
  SERVER_NAME: ${miurl}
