apiVersion: v1
kind: Service
metadata:
  name: conexus-wso2mi
  namespace: ingress-nginx
  labels:
    app: conexus-wso2mi
spec:
  ports:
    - name: https-passthrough 
      port: 8253
      targetPort: 8253
      protocol: TCP
    - name: http-passthrough
      port: 8290
      targetPort: 8290
      protocol: TCP
    - name: http-management
      port: 9201
      targetPort: 9201
      protocol: TCP
    - name: https-management
      port: 9164
      targetPort: 9164
      protocol: TCP
    - name: mi-dashboard 
      port: 9743
      targetPort: 9743
      protocol: TCP
  selector:
    app.kubernetes.io/name: conexus-wso2mi

