apiVersion: v1
kind: ConfigMap
metadata:
  name: jboss-config
  namespace: ingress-nginx
data:
  DB_ENDPOINT: ${db_endpoint}
  DB_USER: ${db_user}
  DB_USER_MOD: ${db_user_mod}
  V_SMTP_HOST: ${smtp_host}
  app_env: ${env}
  
