apiVersion: v1
kind: Service
metadata:
  name: jms
  namespace: ingress-nginx
  labels:
    app: jms
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: jms
