apiVersion: v1
kind: Service
metadata:
  name: avapache
  namespace: ingress-nginx
  labels:
    app: avapache
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: avapache
  externalTrafficPolicy: Local
