apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conexus-httpd-ingress
  namespace: ingress-nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: sandbox.conexus-project.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend: 
            service:
              name: conexus-httpd    
              port:
                number: 80  
