kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-data
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${fs_data}
  directoryPerms: "755"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-data-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-data
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${fs_data}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-data-volume-claim
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-data
  resources:
    requests:
      storage: 5Gi
