apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ui-dev
  namespace: cert-manager
spec:
  dnsNames:
  - "*.dev.cnxs.vpcaas.fcs.gsa.gov"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: wildcard-letsencrypt-staging

