apiVersion: cert-manager.io/v1
kind: ClusterIssuer # ClusterIssuer can issue for all namespaces
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ocio-eas-conexus-systems@usda.gov
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: us-east-1
          #hostedZoneID: Z00469081L8WP3FVPM748
          accessKeyIDSecretRef:
            name: dev-route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: dev-route53-credentials-secret
            key: secret-access-key
          extraArgs:
            
#  - '--dns01-recursive-nameservers-only'
#  - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
          # you can also assume a role with these credentials
          #role: arn:aws:iam::YYYYYYYYYYYY:role/dns-manager          
