apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
  name: letsencrypt-prod-management
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: madhav.kundala@usda.gov
    privateKeySecretRef:
      name: letsencrypt-prod-management
    solvers:
    - http01:
        ingress:
          class: nginx 
