---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ekspodidentity-sa
  namespace: ingress-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ekspodidentity-sa
  namespace: kube-system
