apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-apache-config
  namespace: ingress-nginx
data:
  SERVER_NAME: swagger.test.cnxs.vpcaas.fcs.gsa.gov
  OIDC_PROVIDER_URL: https://gateway.cert.eauth.usda.gov/affwebservices/CASSO/oidc/USDA_GSA_Conexus_v0/.well-known/openid-configuration
  OIDC_CLIENT_ID: 23b3f5fa-ca1d-4405-bd57-ab9269e96f3a
  OIDC_REDIRECT_URI: https://ui.test.cnxs.vpcaas.fcs.gsa.gov/secure/redirect_uri
  OIDC_LOGGEDOUT_URL: https://ui.test.cnxs.vpcaas.fcs.gsa.gov
  OIDC_DEFAULT_URL: https://ui.test.cnxs.vpcaas.fcs.gsa.gov/secure/

 
