apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-apache-config
  namespace: ingress-nginx
data:
  SERVER_NAME: ${swaggerurl}
  OIDC_PROVIDER_URL: ${swaggeroidc_provider_url}
  OIDC_CLIENT_ID: ${swaggeroidc_client_id}
  OIDC_REDIRECT_URI: ${swaggeroidc_redirect_uri}
  OIDC_LOGGEDOUT_URL: ${swaggeroidc_loggedout_url}
  OIDC_DEFAULT_URL: ${swaggeroidc_default_url}

 
