apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-apache-config
  namespace: ingress-nginx
data:
  SERVER_NAME: swagger.dev.cnxs.vpcaas.fcs.gsa.gov
  OIDC_PROVIDER_URL: https://auth-preprod.gsa.gov/.well-known/openid-configuration
  OIDC_CLIENT_ID: 0oah83ogg1CqPpxMC4h7
  OIDC_REDIRECT_URI: https://swagger.dev.cnxs.vpcaas.fcs.gsa.gov
  OIDC_LOGGEDOUT_URL: https://www.google.com
  OIDC_DEFAULT_URL: https://swagger.dev.cnxs.vpcaas.fcs.gsa.gov

 
