apiVersion: v1
kind: Service
metadata:
  name: conexus-swagger-httpd
  namespace: ingress-nginx
  labels:
    app: conexus-swagger-httpd
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  
  selector:
    app.kubernetes.io/name: conexus-swagger-httpd

