apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  auth: |-
    -groups:
      - system:bootstrappers                                                                                                                   
      - system:nodes                                                                                                                           
      rolearn: arn:aws:iam::471112718870:role/cnxsdev-karpenter-node-role
      #username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::471112718870:role/terraformops



