apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-v0.4.0-rc1-8-g312bd89
  creationTimestamp: null
  name: apicilium
  namespace: ingress-nginx
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-mode: "shared"
      service.beta.kubernetes.io/aws-load-balancer-name: "conexus-api-internal-alb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0826111a038991700"
  listeners:
  - hostname: api.dev.cnxs.vpcaas.fcs.gsa.gov
    name: api-http
    port: 80
    protocol: HTTP
  - hostname: api.dev.cnxs.vpcaas.fcs.gsa.gov
    name: api-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: null
        kind: null
        name: devwildcard
  - name: default-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: null
        kind: null
        name: devwildcard        
status: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-v0.4.0-rc1-8-g312bd89
  creationTimestamp: null
  name: conexus-nginx-ingress-api
  namespace: ingress-nginx
spec:
  hostnames:
  - api.dev.cnxs.vpcaas.fcs.gsa.gov
  parentRefs:
  - name: apicilium
  rules:
  - backendRefs:
    - name: conexus-nginx
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: []
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-v0.4.0-rc1-8-g312bd89
  creationTimestamp: null
  name: conexus-api-default-health-check
  namespace: ingress-nginx
spec:
  parentRefs:
  - name: apicilium
  rules:
  - backendRefs:
    - name: conexus-nginx
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: []
